active: dev
datasource:
  url: jdbc:sqlite:im-sync-bot.db
  driver-class-name: org.sqlite.JDBC
  hikari:
    auto-commit: false
jpa:
  database-platform: org.hibernate.community.dialect.SQLiteDialect
  hibernate:
    ddl-auto: create
##################################
####     上面内容不建议改动     #####
##################################
im-sync-bot:
  bot:
    telegram:
      token: 1234567:adgcgasdfadf # tg机器人token
      username: your_bot_name  # tg机器人用户名
    qq:
      host: "localhost"  # onebot 服务端ip/域名
      port: 9000         # onebot 服务端正向连接端口
      token: ""          # onebot 服务端token，没有就不需要动
    master-of-tg: 12345678 #主人 tg id
    master-of-qq: 87654321 #主人 qq 账号