version: '3.5'
services:
  bot:
    build: .  #自行打包镜像则去除该注释
    image: kurenai9/im-sync-bot:latest
    container_name: bot
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    user: root
    volumes:
      - ./data/:/app/data
      - ./config.yaml:/app/application.yaml
      - ./cache:/app/cache
      - ./logs:/app/logs
    depends_on:
      - redis
#      - api  #本地api则去掉注释

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/usr/local/etc/redis
