version: '3.5'
services:
  bot:
#    build: .
    image: kurenai9/im-sync-bot:nightly
    container_name: bot
    restart: always
    environment:
      #      BASE_URL: "http://api:8081/bot"
      REDIS_HOST: "redis"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    volumes:
      - ./api-data:/var/lib/telegram-bot-api/
      - ./device.json:/im-sync-bot/device.json
      - ./cache:/im-sync-bot/cache
      - ./config.yaml:/im-sync-bot/config.yaml
      - ./logs:/im-sync-bot/logs

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    volumes:
      - ./redis-data:/usr/local/etc/redis

  api:
    image: aiogram/telegram-bot-api
    container_name: tg-api
    restart: always
    environment:
      TELEGRAM_API_ID: YOUR_API_ID
      TELEGRAM_API_HASH: YOUR_API_HASH
      TELEGRAM_STAT: 1
      TELEGRAM_LOCAL: 1
      TELEGRAM_VERBOSITY: 4
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - 8081-8082:8081-8082
    volumes:
      - ./api-data:/var/lib/telegram-bot-api
