version: '3.5'
services:
  bot:
    image: kurenai9/im-sync-bot
    restart: always
    volumes:
      - ./data:/var/lib/telegram-bot-api/
      - ./device.json:/im-sync-bot/device.json
      - ./cache:/im-sync-bot/cache
      - ./config.yaml:/im-sync-bot/config.yaml

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/usr/local/etc/redis

