version: '3.5'
services:
  bot:
#    build: .  #自行打包镜像则去除该注释
    image: kurenai9/im-sync-bot:1.2.0
    container_name: bot
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    user: root
    volumes:
      #      - ./api-data/:/var/lib/telegram-bot-api/ #本地api配置
      - ./mirai/:/deployments/mirai/
      - ./config/:/deployments/config/
      - ./config/config.yaml:/deployments/application.yaml
      - ./cache:/deployments/cache
      - ./logs:/deployments/logs
    depends_on:
      - redis
#      - api  #本地api则去掉注释

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    volumes:
      - ./redis-data:/usr/local/etc/redis

#  需要本地api则去除注释
#  api:
#    image: aiogram/telegram-bot-api
#    container_name: tg-api
#    restart: always
#    environment:
#      TELEGRAM_API_ID: YOUR_API_ID
#      TELEGRAM_API_HASH: YOUR_API_HASH
#      TELEGRAM_STAT: 1
#      TELEGRAM_LOCAL: 1
#      TELEGRAM_VERBOSITY: 4
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200m"
#        max-file: "3"
#    ports:
#      - 8081-8082:8081-8082
#    volumes:
#      - ./api-data:/var/lib/telegram-bot-api
