spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./db/im-sync-bot;AUTO_SERVER=TRUE
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false