[versions]
ktolin = "2.2.20"
ksp = "2.2.20-2.0.3"
lombok = "9.0.0-rc2"
serialization = "1.8.1"
coroutines = "1.10.2"
ktor = "3.2.0"
log4j = "2.20.0"
jimmer = "0.9.111"
jackson = "2.19.2"
mirai = "2.16.0"
serialize-xml = "0.91.2"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "ktolin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.0" }
kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version = "0.29.0" }
kotlinx-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-tls = { group = "io.ktor", name = "ktor-network-tls-certificates", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
serialization-yaml = { group = "net.mamoe.yamlkt", name = "yamlkt-jvm", version = "0.13.0" }
serialization-xml-core = { group = "io.github.pdvrieze.xmlutil", name = "core", version.ref = "serialize-xml" }
serialization-xml-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "serialize-xml" }
caffeine = { group = "com.sksamuel.aedile", name = "aedile-core", version = "2.1.2" }
jsoup = { group = "org.jsoup", name = "jsoup", version = "1.20.1" }
directory-watcher = { group = "io.methvin", name = "directory-watcher", version = "0.19.1" }
apache-commons-pool2 = { group = "org.apache.commons", name = "commons-pool2", version = "2.11.1" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.19.0" }
apache-log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
apache-log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
apache-log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
zxing-core = { group = "com.google.zxing", name = "core", version = "3.5.2" }
zxing-javase = { group = "com.google.zxing", name = "javase", version = "3.5.2" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.6" }
diruptor = { group = "com.lmax", name = "disruptor", version = "3.4.4" }
tdlight-bom = { module = "it.tdlight:tdlight-java-bom", version = "3.4.4+td.1.8.52" }
tdlight = { group = "it.tdlight", name = "tdlight-java" }
jimmer-sql-kotlin = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "6.3.0" }
sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.47.0.0" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jdk8 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
mirai-bom = { group = "net.mamoe", name = "mirai-bom", version.ref = "mirai" }
mirai-api = { group = "net.mamoe", name = "mirai-core-api" }
mirai-utils = { group = "net.mamoe", name = "mirai-core-utils" }
mirai-bridge-overflow = { group = "top.mrxiaom.mirai", name = "overflow-core", version = "1.0.7" }
reflections = { group = "org.reflections", name = "reflections", version = "0.10.2" }

[bundles]
ktorClient = ["ktor-client-core", "ktor-client-okhttp", "ktor-serialization-kotlinx-json", "ktor-client-negotiation"]
zxing = ["zxing-core", "zxing-javase"]
log = ["apache-log4j-api", "apache-log4j-core", "apache-log4j-slf4j2", "slf4j-api"]
jackson = ["jackson-module-kotlin", "jackson-datatype-jdk8", "jackson-datatype-jsr310"]
mirai = ["mirai-api", "mirai-utils", "mirai-bridge-overflow"]
serializationXml = ["serialization-xml-core", "serialization-xml-serialization"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "ktolin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "ktolin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "ktolin" }
kotlin-openall = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "ktolin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "ktolin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
openapi-generator = { id = "org.openapi.generator", version = "7.13.0" }
