spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
bot:
  telegram:
    token: 1234567:adgcgasdfadf # tg机器人token
    username: your_bot_name  # tg机器人用户名
  qq:
    account: 12354547  # qq账号
    password: your-qq-password # qq密码
    protocol: ANDROID_PAD #ANDROID_PAD | ANDROID_PHONE | ANDROID_WATCH
  handler:
    forward:
      enable: true  # 开启转发（就算删除也默认开启）
      master-of-tg: 12345678 #主人 tg id
      master-of-qq: 87654321 #主人 qq 账号
      tgMsgFormat: "$name$newline$newline$msg"  #tg消息格式化
      qqMsgFormat: "$name: $msg" # qq消息格式化

logging:
  file:
    name: ./log/im-sync-bot.log