# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Dependence
        id: cache-dependence
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Jar
        id: cache-jar
        uses: actions/cache@v2
        with:
          path: |
            build/libs/
          key: ${{ runner.os }}-gradle-${{ hashFiles('src/*', 'bin/*', '**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run unit test
        if: steps.cache-jar.outputs.cache-hit != 'true'
        run: ./gradlew test
      - name: Upload coverage reports to Codecov
        if: steps.cache-jar.outputs.cache-hit != 'true'
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
      - name: Build with Gradle
        if: steps.cache-jar.outputs.cache-hit != 'true'
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: im-sync-bot
          path: build/libs/
